# Generated by Django 5.0.3 on 2024-06-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('alcohol_type', models.CharField(choices=[('WHISKEY', 'Whiskey'), ('VODKA', 'Vodka'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('RUM', 'Rum'), ('GIN', 'Gin'), ('TEQUILA', 'Tequila'), ('BRANDY', 'Brandy'), ('LIQUEUR', 'Liqueur'), ('OTHER', 'Other')], max_length=50, verbose_name='Тип')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бутылка',
                'verbose_name_plural': 'Бутылки',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
