# Generated by Django 5.0.3 on 2024-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_bottle_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottle_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='alcohol_type',
            field=models.CharField(choices=[('WHISKEY', 'Whiskey'), ('VODKA', 'Vodka'), ('WINE', 'Wine'), ('BEER', 'Beer'), ('RUM', 'Rum'), ('GIN', 'Gin'), ('TEQUILA', 'Tequila'), ('BRANDY', 'Brandy'), ('LIQUEUR', 'Liqueur'), ('OTHER', 'Other')], max_length=50, verbose_name='Тип алкоголя'),
        ),
    ]
